### ISSUE TITLE
submit a PR at flipace/lovli.js

### ISSUE THREAD

**Issue by jokeyrhyme** [redux-bootstrap/redux-bootstrap#24]
https://github.com/flipace/lovli.js looks like a starter kit that could be a good fit for redux-bootstrap.

**Comment by remojansen** [comment]
Awesome :smile: sorry about not doing a lot of work on the project over the last couple of weeks [inversify](https://github.com/inversify) is taking all my time but I'm working on a [chrome app](https://github.com/inversify/inversify-devtools) that uses redux-bootstrap. Once I'm done I will use a lot of the code in the redux-bootstrap example app.

**Comment by remojansen** [comment]
Closing this issue for now. I'm working on an updated example with webpack will be available soon.
