### ISSUE TITLE
submit a PR at xgrommx/awesome-redux

### ISSUE THREAD

**Issue by jokeyrhyme** [redux-bootstrap/redux-bootstrap#27]
https://github.com/xgrommx/awesome-redux

**Comment by jokeyrhyme** [comment]
Done: https://github.com/xgrommx/awesome-redux/pull/197

**Comment by remojansen** [comment]
Thanks for all the work I really appreciate it :)

**Comment by jokeyrhyme** [comment]
I personally find this project useful, and I'm sure others will as well.
