### ISSUE TITLE
Update this GitHub repo’s description

### ISSUE THREAD

**Issue by roryokane** [redux-bootstrap/redux-bootstrap#33]
Currently, it is

>  Bootstrapping function for Redux applications. 

It should be changed to match the first sentence of [the README](https://github.com/redux-bootstrap/redux-bootstrap/blob/master/README.md), which was recently updated:

> A bootstrap() function for initializing Redux applications.

This new sentence explains that this library helps with initializing, and clarifies that “function” refers to a JS function as opposed to some functionality.

To update the description, a user with commit rights can visit [the project root](https://github.com/redux-bootstrap/redux-bootstrap) and click the “Edit” link next to the description at the top.

**Comment by jokeyrhyme** [comment]
I think only @remojansen can action this one.

**Comment by remojansen** [comment]
I just updated I like the new description thanks for suggesting it 👍
