### ISSUE TITLE
consider recommending inversify instead of redux `connect()` ?

### ISSUE THREAD

**Issue by jokeyrhyme** [redux-bootstrap/redux-bootstrap#52]
I just read this article:
- http://blog.wolksoftware.com/dependency-injection-in-react-powered-inversifyjs

It's pretty interesting, and I'm wondering now whether it's worth exploring this?

I think we'd need to see some side-by-side examples, and compare how things currently work with `connect()` versus how they would work in practice using [inversify](https://github.com/inversify/InversifyJS).

I'm not especially sold on the mocking benefits, because it is likely common practice to `export` both the original React component _and_ its `connect()`ed equivalent.

Of course, inversify opens the door for other things beyond redux, so there's that. /shrug

**Comment by remojansen** [comment]
Hi @jokeyrhyme I'm the author of that article and the author of InversifyJS. Right now I want to complete two tasks on InversifyJS that will allow me to develop another utility for Redux: https://github.com/redux-bootstrap/libertad

Libertad is based in the ideas from that article. I will release it and see how people think about it. If it becomes very popular I will probably think about including it with redux-bootstrap but I think is important to see how people feel about it first.

**Comment by remojansen** [comment]
Closing this because is going to be a long time before libertad becomes stable (I have very little free time at the moment).
